
# Phil Hayward, 24th October 2014
#

# makeCacheMatrix relies on lexical scoping to save a state and data in an environment 
# (i.e. the environment of the function makeCacheMatrix)
# in this case the state is a set of functions, a matrix and its inverse if it's stored 
# This function doesn't do any work, in itself - it just stores data calculated elsewhere
# And returns the inverse if present when asked 
#
# A typical set of calls would be:
#
# [1] makeCacheMatrix - initialised the function 
# [2] call to set - set the underlying matrix (actually the inverse could have been generated at this point too, but not in this case)
# [3] call to setInvertedMatrix (which is generated by its calling function here with a matrix which has been solved )
# [4] call to getInvertedMatrix - returns the inverted matrix which was previously stored there.. 
#


makeCacheMatrix <- function(x = matrix()) {
  
  # Initialise inverted matrix 
  InvertedMatrix <- NULL  
  
  # Save a new matrix which we are going to solve (outside the function) 
  saveNewMatrix <- function(newMatrix)
  {
    x<- newMatrix 
    InvertedMatrix <- NULL # Reset invereted matrix 
  }
  
  # Get/Set for the underlying matrix 
  set <- function(y) { x <- x }
  get <- function()  { x }
  
  # Get/Set for the inverted matrix 
  getInvertedMatrix <- function() { InvertedMatrix }                              # Get the cache matrix if present 
  setInvertedMatrix <- function(justInverted) { InvertedMatrix <<- justInverted } # Save the newly inverted matrix 
  
  # Return from makeCacheMatrix: a set of functions. 
  list(
    set=set,
    get=get,
    setInvertedMatrix=setInvertedMatrix, 
    getInvertedMatrix=getInvertedMatrix    
    )
}

# The driving function/caller for makeCacheMatrix, in this case the formal parametr "X" is the 
# makeCacheMatrix function instance 

cacheSolve <- function(x, ...) {
  
  InvertedMatrix <- x$getInvertedMatrix()
  
  if (!is.null(InvertedMatrix)) {
    # Cached matrix IS present - lets get it back 
    message("Cached object present now... so just returning cache object")
    InvertedMatrix <- x$getInvertedMatrix() # Get the one which was solved already  
  }
  else {
    # No cached matrix present - lets make one and save it 
    message("No cached object, so solving and storing...")
    NonInvertedMatrix <- x$get()  # Get underlying matrix (not inverted)
    InvertedMatrix <- solve(NonInvertedMatrix)   # Solve it 
    x$setInvertedMatrix(InvertedMatrix) # Stick it back in the cache 
  }
  
  
  # Result 
  InvertedMatrix
}


